-- RoutineSync / FECIP 2026 - ETERJ
-- Estrutura básica para Supabase (PostgreSQL)

create table if not exists public.resultados (
    id bigint generated by default as identity primary key,
    nome text not null,
    idade smallint not null check (idade between 1 and 120),
    objetivo text not null check (objetivo in ('food', 'productivity')),
    pontuacao smallint not null check (pontuacao between 0 and 100),
    respostas jsonb not null default '{}'::jsonb,
    criado_em timestamptz not null default now()
);

alter table public.resultados enable row level security;

grant insert on table public.resultados to anon, authenticated;

drop policy if exists "Permitir inserir resultados" on public.resultados;

create policy "Permitir inserir resultados"
on public.resultados
for insert
to anon, authenticated
with check (true);

-- Não há política de SELECT público.
-- Os dados ficam visíveis no painel do Supabase para a demonstração da banca.
